### PR TITLE
Fix for fuzzy search

### LINKED ISSUE #50: !gif command should fuzzy match query terms
Current behavior of !gif:
```
username [2:30 PM]
!gif --explicit ed-209 robocop

IQVBOT APP [2:30 PM]
No gifs matching query 'ed-209 robocop'
```

As opposed to querying tenor directly:
https://tenor.com/search/ed-209-robocop-gifs

### PR DESCRIPTION
**Pull request by nehayward**
This changes the endpoint to search, it was set to **random** by mistake.

ed 209 robocop is operationally 

close #50

### CODE REVIEW

File: bot/gif_command.go [hunk 1]
```diff
@@ -45,13 +45,13 @@ func NewGIFCommand(endpoint, key string, w io.Writer) cli.Command {
 			query := url.Values{}
 			query.Set("key", key)
 			query.Set("q", strings.Join(args, " "))
-			query.Set("limit", "1")
+			query.Set("mediafilter", "minimal")
 			if !c.Bool("explicit") {
 				query.Set("safesearch", "strict")
```
Comment (zpatrick) [inline bot/gif_command.go]: Looking at their [docs](https://tenor.com/gifapi/documentation#endpoints-search): this should be a string flag, and in the usage we show the options: 'off', 'moderate', 'mild', or 'strict'

File: bot/gif_command.go [hunk 2]
```diff
@@ -45,13 +45,13 @@ func NewGIFCommand(endpoint, key string, w io.Writer) cli.Command {
 			query := url.Values{}
 			query.Set("key", key)
 			query.Set("q", strings.Join(args, " "))
-			query.Set("limit", "1")
```
Comment (zpatrick) [inline bot/gif_command.go]: Limit should also be an integer flag with the default value shown in their [docs](https://tenor.com/gifapi/documentation#endpoints-search): 20

File: bot/gif_command.go [hunk 3]
```diff
@@ -45,13 +45,13 @@ func NewGIFCommand(endpoint, key string, w io.Writer) cli.Command {
...
+			query.Set("mediafilter", "minimal")
 			if !c.Bool("explicit") {
 				query.Set("safesearch", "strict")
 			}
 
 			var response TenorSearchResponse
-			if err := client.Get("/v1/random", &response, rclient.Query(query)); err != nil {
+			if err := client.Get("/v1/search", &response, rclient.Query(query)); err != nil {
```
Comment (zpatrick) [inline bot/gif_command.go]: since we are switching from random back to search, you should grab a random gif out of the response.

**Comment by zpatrick** [comment]
@nehayward for the record, it was not set to `/random` by mistake. I made that change because using the `/search` endpoint returns the same result every time

File: bot/gif_command.go (hunk 3 above)
Comment (nehayward) [reply bot/gif_command.go]: I'm not sure, since most people use the !gif almost like a map, where you enter `phrase` and get results, this would break that paradigm. Maybe we could add a random flag instead?

**Comment by nehayward** [comment]
@zpatrick interesting, I think some other stuff is going on with `/random` too. Maybe it lacks fuzzy search, since changing it resulted in a lot more results.

File: bot/gif_command.go (hunk 1 above)
Comment (nehayward) [reply bot/gif_command.go]: Yeah but in practice I think people use it more in a binary sense. I don't think anyone will use it with those flags IMO, I just want it strict or off.

File: bot/gif_command.go (hunk 3 above)
Comment (zpatrick) [reply bot/gif_command.go]: I don't think we're on the same page here; nothing would change from the user's perspective. 
My suggestion was geared towards fixing the problem I was originally trying to solve by switching from `/search` to `/random`

Comment (nehayward) [reply bot/gif_command.go]: I think it should change from the user perspective, as in typing a phrase should return the same result.

File: bot/gif_command.go (hunk 1 above)
Comment (zpatrick) [reply bot/gif_command.go]: Good point - let's keep the bool flag then. 

Now that I'm looking at it, I think this needs to be:
```go
query.Set("safesearch", "strict")
if c.Bool("explicit") {
    query.Set("safesearch", "off")
}
```

File: bot/gif_command.go (hunk 3 above)
Comment (zpatrick) [reply bot/gif_command.go]: Hmmm, not sure how I feel about that. 
I'm fairly confident everyone who already uses !gif would prefer the random behavior by default; 
However I wouldn't be opposed to adding a `--random` flag and then creating an alias: 
```
!alias add !gif "!gif --random --limit 50"
```
